# Generated by Django 5.1.5 on 2025-03-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_thumbnails/"
            ),
        ),
    ]
