# Generated by Django 5.1.5 on 2025-04-08 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_course_thumbnail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="enrolled_course",
            new_name="enrolled_courses",
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="completion_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="completed_lessons",
            field=models.ManyToManyField(
                blank=True, related_name="completed_by", to="courses.lesson"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
